-- Terminals Table
-- Tracks active AI coding assistants across users/pueblos
-- Agnostic to the client (Claude Code, Cursor, Codex, Copilot, etc.)

-- 1. Pueblos table (if not exists from previous migration)
CREATE TABLE IF NOT EXISTS pueblos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre TEXT NOT NULL,
  owner_id UUID,                           -- Optional FK to auth.users
  owner_name TEXT NOT NULL,                -- Display name (Aitzol, Sergi, Alvaro)
  avatar_emoji TEXT DEFAULT '👤',
  color_primary TEXT DEFAULT '#3b82f6',
  color_secondary TEXT DEFAULT '#1e40af',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pueblos_owner_name ON pueblos(owner_name);
CREATE INDEX IF NOT EXISTS idx_pueblos_active ON pueblos(is_active);

-- RLS for pueblos
ALTER TABLE pueblos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read pueblos" ON pueblos FOR SELECT USING (true);
CREATE POLICY "Allow insert pueblos" ON pueblos FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update pueblos" ON pueblos FOR UPDATE USING (true);

-- 2. Terminals table
CREATE TABLE IF NOT EXISTS terminals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pueblo_id UUID REFERENCES pueblos(id) ON DELETE CASCADE,

  -- Terminal identification
  name TEXT NOT NULL,                      -- User-friendly name: "Mi Claude Code", "Laptop Cursor"
  client_type TEXT NOT NULL,               -- "claude-code", "cursor", "codex", "copilot", "aider", "other"
  session_id TEXT NOT NULL,                -- Unique session identifier (generated by client)
  machine_id TEXT,                         -- Optional: machine fingerprint for grouping

  -- Status
  status TEXT NOT NULL DEFAULT 'offline'
    CHECK (status IN ('active', 'thinking', 'coding', 'idle', 'offline')),
  current_task TEXT,                       -- What the terminal is working on
  current_file TEXT,                       -- File being edited (optional)
  speech_bubble TEXT,                      -- Fun message to show in UI

  -- Metrics
  tasks_completed INTEGER DEFAULT 0,
  lines_written INTEGER DEFAULT 0,
  energy INTEGER DEFAULT 100,              -- Visual energy bar (0-100)

  -- Connection
  last_heartbeat TIMESTAMPTZ DEFAULT now(),
  ip_address INET,                         -- For geo display (optional)

  -- Metadata
  metadata JSONB DEFAULT '{}',             -- Additional client-specific data

  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),

  -- Ensure unique sessions per pueblo
  CONSTRAINT unique_session UNIQUE (pueblo_id, session_id)
);

CREATE INDEX IF NOT EXISTS idx_terminals_pueblo ON terminals(pueblo_id);
CREATE INDEX IF NOT EXISTS idx_terminals_status ON terminals(status);
CREATE INDEX IF NOT EXISTS idx_terminals_heartbeat ON terminals(last_heartbeat DESC);
CREATE INDEX IF NOT EXISTS idx_terminals_session ON terminals(session_id);

-- RLS for terminals
ALTER TABLE terminals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read terminals" ON terminals FOR SELECT USING (true);
CREATE POLICY "Allow upsert terminals" ON terminals FOR ALL USING (true) WITH CHECK (true);

-- 3. Terminal activity log (recent actions for the feed)
CREATE TABLE IF NOT EXISTS terminal_activity (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  terminal_id UUID REFERENCES terminals(id) ON DELETE CASCADE,
  pueblo_id UUID REFERENCES pueblos(id) ON DELETE CASCADE,

  action_type TEXT NOT NULL
    CHECK (action_type IN ('task_start', 'task_complete', 'file_edit', 'commit', 'error', 'message', 'status_change')),
  description TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',

  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_terminal_activity_terminal ON terminal_activity(terminal_id);
CREATE INDEX IF NOT EXISTS idx_terminal_activity_pueblo ON terminal_activity(pueblo_id);
CREATE INDEX IF NOT EXISTS idx_terminal_activity_time ON terminal_activity(created_at DESC);

-- RLS for activity
ALTER TABLE terminal_activity ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read activity" ON terminal_activity FOR SELECT USING (true);
CREATE POLICY "Allow insert activity" ON terminal_activity FOR INSERT WITH CHECK (true);

-- 4. Pueblo stats table (aggregated stats per pueblo)
CREATE TABLE IF NOT EXISTS pueblo_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pueblo_id UUID UNIQUE REFERENCES pueblos(id) ON DELETE CASCADE,

  terminals_active INTEGER DEFAULT 0,
  terminals_total INTEGER DEFAULT 0,

  tasks_pending INTEGER DEFAULT 0,
  tasks_completed_today INTEGER DEFAULT 0,
  tasks_completed_total INTEGER DEFAULT 0,

  energy_current INTEGER DEFAULT 100,
  energy_max INTEGER DEFAULT 100,

  coins_total INTEGER DEFAULT 0,
  coins_today INTEGER DEFAULT 0,
  streak_days INTEGER DEFAULT 0,

  ralph_state TEXT DEFAULT 'idle'
    CHECK (ralph_state IN ('idle', 'walking', 'building', 'thinking', 'disconnected')),
  ralph_last_seen TIMESTAMPTZ DEFAULT now(),

  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pueblo_stats_pueblo ON pueblo_stats(pueblo_id);

-- RLS for pueblo_stats
ALTER TABLE pueblo_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read pueblo_stats" ON pueblo_stats FOR SELECT USING (true);
CREATE POLICY "Allow upsert pueblo_stats" ON pueblo_stats FOR ALL USING (true) WITH CHECK (true);

-- 5. Function to auto-update pueblo stats when terminals change
CREATE OR REPLACE FUNCTION update_pueblo_terminal_stats()
RETURNS TRIGGER AS $$
BEGIN
  -- Update active terminal count for the pueblo
  UPDATE pueblo_stats
  SET
    terminals_active = (
      SELECT COUNT(*) FROM terminals
      WHERE pueblo_id = COALESCE(NEW.pueblo_id, OLD.pueblo_id)
      AND status != 'offline'
      AND last_heartbeat > now() - interval '2 minutes'
    ),
    terminals_total = (
      SELECT COUNT(*) FROM terminals
      WHERE pueblo_id = COALESCE(NEW.pueblo_id, OLD.pueblo_id)
    ),
    updated_at = now()
  WHERE pueblo_id = COALESCE(NEW.pueblo_id, OLD.pueblo_id);

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_pueblo_stats_on_terminal_change
  AFTER INSERT OR UPDATE OR DELETE ON terminals
  FOR EACH ROW
  EXECUTE FUNCTION update_pueblo_terminal_stats();

-- 6. Function to mark terminals as offline if no heartbeat
CREATE OR REPLACE FUNCTION mark_stale_terminals_offline()
RETURNS void AS $$
BEGIN
  UPDATE terminals
  SET status = 'offline', updated_at = now()
  WHERE status != 'offline'
  AND last_heartbeat < now() - interval '2 minutes';
END;
$$ LANGUAGE plpgsql;

-- 7. Insert default pueblos
INSERT INTO pueblos (nombre, owner_name, avatar_emoji, color_primary, color_secondary) VALUES
  ('Pueblo de Aitzol', 'Aitzol', '👨‍💻', '#3b82f6', '#1e40af'),
  ('Pueblo de Sergi', 'Sergi', '🧑‍💻', '#10b981', '#047857'),
  ('Pueblo de Alvaro', 'Alvaro', '👩‍💻', '#f59e0b', '#d97706')
ON CONFLICT DO NOTHING;

-- 8. Initialize pueblo_stats for each pueblo
INSERT INTO pueblo_stats (pueblo_id)
SELECT id FROM pueblos
ON CONFLICT (pueblo_id) DO NOTHING;

-- Comments
COMMENT ON TABLE terminals IS 'Active AI coding assistant sessions (Claude Code, Cursor, Codex, etc.)';
COMMENT ON TABLE terminal_activity IS 'Activity feed for terminals';
COMMENT ON TABLE pueblo_stats IS 'Aggregated statistics per pueblo';
COMMENT ON COLUMN terminals.client_type IS 'Type of AI client: claude-code, cursor, codex, copilot, aider, other';
COMMENT ON COLUMN terminals.session_id IS 'Unique session ID generated by the client on startup';
